#!/bin/sh
ICON=~/.config/mako/icons/brightness.png

  case "$1" in
  "--inc")
	brightnessctl set +5% && notify-send -h string:x-canonical-private-synchronous:sys-notify  -i "$ICON" "$(brightnessctl -m | cut -d, -f4)"
    ;;
  "--dec")
    brightnessctl set 5%- &&	notify-send -h string:x-canonical-private-synchronous:sys-notify  -i "$ICON" "$(brightnessctl -m | cut -d, -f4)"
	;;
  esac

