#!/bin/sh
brightness=$(brightnessctl g ) 
full_brightness=937
brightness_percentage=$(expr $brightness \* 100 / $full_brightness)
killall mako
notify-send -i  "Brightness " " $brightness_percentage% "
